#!/bin/sh
# install-app app
#  assumes your directory is ~/public_html/esglobe
d=~/public_html/esglobe

wget -O /tmp/$1.tgz\
 https://github.com/grflierl/esglobe-apps/blob/master/$1.tgz?raw=true

cd $d
tar -xzvf /tmp/$1.tgz
cd $1
[ -e install ] && . install
